version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    restart: always
    env_file: "./.env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_URL=${MYSQL_URL}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local